### PR TITLE
Remove dependence on Tomcat.

### PR DESCRIPTION
**Pull request by michaeldever**
Replaced MemoryUserDatabase with custom UserDatabase:
* Uses a separate h2 database to Webgoats hysql to prevent conflicts.
* Introduces new UserDatabase mimicking the behaviour of MemoryUserDatabase
* Introduces a dependency on h2.

### CODE REVIEW

**Comment by mayhew64** [comment]
We need to ensure these changes get moved into WebGoat.

**Comment by nbaars** [comment]
I will merge the pull request and merge the changes to WebGoat-Container as well.

**Comment by nbaars** [comment]
Merged the changes locally, but the following error occurred during compilation:

```
[ERROR] COMPILATION ERROR :                                                                                                                                                                          
[INFO] -------------------------------------------------------------                                                                                                                                 
[ERROR] /c:/workspace/WebGoat-Legacy/src/main/java/org/owasp/webgoat/session/UserDatabase.java:[41,46] unreported exception java.lang.ClassNotFoundException; must be caught or declared to be thrown
[INFO] 1 error                                                                                                                                                                                       
[INFO] -------------------------------------------------------------                                                                                          ```

**Comment by nbaars** [comment]
During loading of the classes the following exception is thrown which results in error page on the website

```
java.lang.NoClassDefFoundError: Could not initialize class org.owasp.webgoat.session.UserTracker
```
The Course#loadLessons is the source of this exception, the catch Exception does not include the NoClassDefFoundError.

**Comment by nbaars** [comment]
Previous one is fixed, during startup the following error occurs:

```
Error Message: Could not initialize class org.owasp.webgoat.session.UserTracker
java.lang.NoClassDefFoundError: Could not initialize class org.owasp.webgoat.session.UserTracker
at org.owasp.webgoat.session.Screen.getLessonTracker(Screen.java:119)
at org.owasp.webgoat.HammerHead.doPost(HammerHead.java:166)
at org.owasp.webgoat.HammerHead.doGet(HammerHead.java:106)
```

**Comment by michaeldever** [comment]
This now builds and runs for me, it was running before too, perhaps I forgot to mvn clean before building previously.

**Comment by michaeldever** [comment]
@nbaars Depending on where you caught the ClassNotFoundException, I can see the issues that followed arising, however, adding it to the UserDatabase class stops it propagating up.

**Comment by nbaars** [comment]
@michaeldever yes I did add it in the UserDatabase class but later on the Course class performs a newInstance() of each class in order to find out whether it is a lesson or not. This fails because UserTracker has private constructor which then throw a NoClassDefFoundError.

**Comment by michaeldever** [comment]
@nbaars Have you re-tried with the commits I just pushed. I see no errors here on my end. Can you list the commands/actions you take to cause the error?

**Comment by nbaars** [comment]
@michaeldever just pulled the changes made a change to the course class while loading the lessons the loading continues(lessons are loaded now this is another error) but fails when opening the webpage:

```
Error Message: Could not initialize class org.owasp.webgoat.session.UserTracker
java.lang.NoClassDefFoundError: Could not initialize class org.owasp.webgoat.session.UserTracker
at org.owasp.webgoat.session.Screen.getLessonTracker(Screen.java:119)
at org.owasp.webgoat.HammerHead.doPost(HammerHead.java:166)
at org.owasp.webgoat.HammerHead.doGet(HammerHead.java:106)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
```

**Comment by nbaars** [comment]
Aha tracked it down, this code:

```
public boolean open() {
		try {
			if (userDB == null || userDB.isClosed()) {
				Class.forName("org.h2.Driver");
				userDB = DriverManager.getConnection(USER_DB_URI, "webgoat_admin", "");
			}
		} catch (SQLException e) {
			logger.error("Unable to connect to the database", e);
			return false;
		} catch (ClassNotFoundException e) {
			logger.error("Class org.h2.Driver not found", e);
			return false;
		}
		return true;
	}
```
gives:

```
org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: The filename, directory name, or volume label syntax is incorrect"; "userDatabase:./users.mv.db" [90031-187]
```

Probably because I'm working on a Windows machine.

**Comment by michaeldever** [comment]
This should be resolved now.

**Comment by nbaars** [comment]
Yes it works I will merge the pull request. I will also merge it to the container.

**Pull request merged**
